// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SistemaEmissaoNF.Faturamento.Infrastructure.Context;

#nullable disable

namespace SistemaEmissaoNF.Faturamento.Infrastructure.Migrations
{
    [DbContext(typeof(FaturamentoDbContext))]
    partial class FaturamentoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("nota_fiscal_numero_seq");

            modelBuilder.Entity("SistemaEmissaoNF.Faturamento.Domain.Entities.NotaFiscal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long>("NumeroSequencial")
                        .HasColumnType("bigint")
                        .HasColumnName("numero_sequencial");

                    b.Property<byte[]>("PdfArquivo")
                        .HasColumnType("bytea")
                        .HasColumnName("pdf_arquivo");

                    b.Property<DateTime?>("PdfGeradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("pdf_gerado_em");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("char(1)")
                        .HasColumnName("status");

                    b.Property<string>("StatusImpressao")
                        .IsRequired()
                        .HasColumnType("char(1)")
                        .HasColumnName("status_impressao");

                    b.HasKey("Id");

                    b.HasIndex("NumeroSequencial")
                        .IsUnique();

                    b.ToTable("nota_fiscal", (string)null);
                });

            modelBuilder.Entity("SistemaEmissaoNF.Faturamento.Domain.Entities.NotaFiscalItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("NotaFiscalId")
                        .HasColumnType("integer")
                        .HasColumnName("nota_fiscal_id");

                    b.Property<long>("ProdutoCodigo")
                        .HasColumnType("bigint")
                        .HasColumnName("produto_codigo");

                    b.Property<string>("ProdutoDescricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("produto_descricao");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("integer")
                        .HasColumnName("produto_id");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade");

                    b.HasKey("Id");

                    b.HasIndex("NotaFiscalId", "ProdutoId")
                        .IsUnique();

                    b.ToTable("nota_fiscal_item", (string)null);
                });

            modelBuilder.Entity("SistemaEmissaoNF.Faturamento.Domain.Entities.NotaFiscalItem", b =>
                {
                    b.HasOne("SistemaEmissaoNF.Faturamento.Domain.Entities.NotaFiscal", "NotaFiscal")
                        .WithMany("Itens")
                        .HasForeignKey("NotaFiscalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NotaFiscal");
                });

            modelBuilder.Entity("SistemaEmissaoNF.Faturamento.Domain.Entities.NotaFiscal", b =>
                {
                    b.Navigation("Itens");
                });
#pragma warning restore 612, 618
        }
    }
}
